#!/usr/bin/env bash

set -e

ROSDISTRO="$(rosversion -d)"
ARCH="$(uname -m)"
echo $ARCH
echo "

 ██████╗ ███╗   ██╗██╗███╗   ██╗███████╗
██╔═══██╗████╗  ██║██║████╗  ██║██╔════╝
██║   ██║██╔██╗ ██║██║██╔██╗ ██║█████╗  
██║   ██║██║╚██╗██║██║██║╚██╗██║██╔══╝  
╚██████╔╝██║ ╚████║██║██║ ╚████║███████╗
 ╚═════╝ ╚═╝  ╚═══╝╚═╝╚═╝  ╚═══╝╚══════╝
   
          http://linorobot.org                                                                          
"

echo -n "You are installing ROS-$ROSDISTRO Onine. Enter [y] to continue. " 
read reply
if [[ "$reply" != "y" && "$reply" != "Y" ]]
    then
        echo "Wrong input. Exiting now"
        exit 1
fi

echo
echo "INSTALLING NOW...."
echo

sudo apt-get update
sudo apt-get install -y avahi-daemon
sudo apt-get install -y openssh-server
sudo apt-get install -y python-setuptools 
sudo apt-get install -y python-dev 
sudo apt-get install -y build-essential
sudo apt-get install -y python-gudev

sudo easy_install pip
sudo pip install -U platformio
sudo rm -rf ~/.platformio/

source /opt/ros/$ROSDISTRO/setup.bash

sudo apt-get install -y ros-$ROSDISTRO-freenect-launch
sudo apt-get install -y ros-$ROSDISTRO-pointcloud-to-laserscan

sudo apt-get install -y ros-$ROSDISTRO-moveit
sudo apt-get install -y ros-$ROSDISTRO-robot-state-publisher
sudo apt-get install -y ros-$ROSDISTRO-joint-state-publisher
sudo apt-get install -y ros-$ROSDISTRO-trac-ik-kinematics-plugin
sudo apt-get install -y ros-$ROSDISTRO-ar-track-alvar

cd
mkdir -p onine_ws/src
cd onine_ws/src
catkin_init_workspace

# Download and build Onine package
git clone https://github.com/grassjelly/onine.git
cd ~/onine_ws
catkin_make

TRAVIS_BRANCH="echo $TRAVIS_BRANCH"
if [ "$TRAVIS_BRANCH" = "devel" ]; then git checkout devel; fi

cd ~/onine_ws/src/onine/firmware/arm_child
export PLATFORMIO_CI_SRC=$PWD/src/firmware.ino
platformio ci --project-conf=./platformio.ini --lib="./lib/braccio"

cd ~/onine_ws/src/onine/firmware/arm_parent
export PLATFORMIO_CI_SRC=$PWD/src/firmware.ino
platformio ci --project-conf=./platformio.ini --lib="./lib/TeensyStep" --lib="./lib/ros_lib"

echo
echo "INSTALLATION DONE!"
echo